########################################################################################################
###███╗   ███╗██╗   ██╗███████╗████████╗███████╗██████╗ ██╗   ██╗██╗  ██╗██╗   ██╗███╗   ██╗████████╗###
###████╗ ████║╚██╗ ██╔╝██╔════╝╚══██╔══╝██╔════╝██╔══██╗╚██╗ ██╔╝██║  ██║██║   ██║████╗  ██║╚══██╔══╝###
###██╔████╔██║ ╚████╔╝ ███████╗   ██║   █████╗  ██████╔╝ ╚████╔╝ ███████║██║   ██║██╔██╗ ██║   ██║   ###
###██║╚██╔╝██║  ╚██╔╝  ╚════██║   ██║   ██╔══╝  ██╔══██╗  ╚██╔╝  ██╔══██║██║   ██║██║╚██╗██║   ██║   ###
###██║ ╚═╝ ██║   ██║   ███████║   ██║   ███████╗██║  ██║   ██║   ██║  ██║╚██████╔╝██║ ╚████║   ██║   ###
###╚═╝     ╚═╝   ╚═╝   ╚══════╝   ╚═╝   ╚══════╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═══╝   ╚═╝   ###
###                                            _            _   __   __                              ###
###                            __ _____ _ _ __(_)___ _ _   / | /  \ /  \                             ###
###                            \ V / -_) '_(_-< / _ \ ' \  | || () | () |                            ###
###                             \_/\___|_| /__/_\___/_||_| |_(_)__(_)__/                             ###
###                                                                                                  ###
########################################################################################################
###> Use & for color-codes. Example: &4, &a, &o | Placeholders: %player% %world%                    <###
###> %p_x% %p_y% %p_z%                                                                              <###
messages:
  prefix: "&5Mystery&c&lHunt &7» "
########################################################################################################
###> Hunting-Tool Customization                                                                     <###
huntingtool:
  material: "COMPASS"
  name: "&5&lHunting&cTool"
  lore:
    - "&8Hint: Right-click to find the"
    - "&8nearest treasure!"
########################################################################################################
###> Reward types: item, command | spawn-delay in SECONDS!                                          <###
treasures:
  "basic":
    broadcast: "&aA &fbasic &atreasure has been found in the world %world%!"
    spawn-worlds:
      - world
    min-players: 1
    rewards-amount: "3-4"
    rewards:
      "0":
        type: command
        value: "give %player% diamond 1"
        amount: "1"
      "1":
        type: item
        value: "IRON_ORE"
        amount: "5-10"
        name: "&bIron Ore"
        lore:
          - "&bExciting ore!"
          - "&bKeep mining it!"
        enchantments:
          - "DURABILITY 1"
      "2":
        type: command
        value: "give %player% bread 10"
        amount: "2"
      "3":
        type: command
        value: "give %player% apple 15"
        amount: "1-2"
    distances:
      max-distance: 2000.0
      min-distance: 1000.0
    open-permission: mysteryhunt.treasure.basic
    spawn-delay: 60
    same-rewards: false
    block-underneath: "GLOWSTONE"
    despawn-delay: 120
    fall-from-sky: true